@url = http://localhost:8080

@token = siSpUIzFjmmyWtI2EMxu8ZVL6PHbxAfY1dIIPIkgXMcScc4iilDWtRzHEviUVQZ9tJlGd4ltCdmBjupBYaHTLzbHZwYDGlIAUl9gBUfM5aQAGbLtC1tO6eRGTSeI68eFD89HcRj9emlqq

###
GET {{url}}/colaboradores
Authorization: Bearer {{token}}

###
GET {{url}}/colaboradores/1
Authorization: Bearer {{token}}

###
POST {{url}}/colaboradores
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nome": "Nome"
}

###
PUT {{url}}/colaboradores/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "titulo": "Título - Alterado"
}

###
DELETE {{url}}/colaboradores/1
Authorization: Bearer {{token}}