@url = http://localhost:8080

@token = siSpUIzFjmmyWtI2EMxu8ZVL6PHbxAfY1dIIPIkgXMcScc4iilDWtRzHEviUVQZ9tJlGd4ltCdmBjupBYaHTLzbHZwYDGlIAUl9gBUfM5aQAGbLtC1tO6eRGTSeI68eFD89HcRj9emlqq

###
GET {{url}}/tarefas
Authorization: Bearer {{token}}

###
GET {{url}}/tarefas/1
Authorization: Bearer {{token}}

###
POST {{url}}/tarefas
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "titulo": "Título",
    "descricao": "Descrição",
    "dataInicio": "2024-11-18",
    "dataConclusao": "2024-11-30"
}

###
PUT {{url}}/tarefas/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "titulo": "Título - Alterado"
}

###
DELETE {{url}}/tarefas/1
Authorization: Bearer {{token}}

###
POST {{url}}/tarefas/1/colaboradores/1
Authorization: Bearer {{token}}

###
DELETE {{url}}/tarefas/1/colaboradores/1
Authorization: Bearer {{token}}